// Package java emits Java records and enums from a checked IR. One file
// per model, enum, and view, per the M1 brief. Scope cuts made explicit
// here rather than silently skipped:
//
//   - No Bean Validation annotations, ever — the brief's frozen decision
//     is that only the WASM engine validates; codegen only shapes data.
//   - Default values aren't applied here. Records can't give constructor
//     parameters default values anyway, and applying a default is a
//     validation-time concern (a pass after required/shape checking),
//     not a type-shape concern — see the M2 rule compiler, not M1 codegen.
//   - "json" always maps to JsonNode, with or without an inline shape:
//     the inline shape is a future structural-validation input, not a
//     generated nested type in M1.
//   - Naming is never transformed here (case conversion, escaping): the
//     brief requires that in the emitter, but since the DSL's own field
//     and type names already double as their Java/TS spelling by
//     convention, "the transform" is the identity function plus the
//     reserved-word rejection in internal/core.CheckNaming, which must
//     run (and pass) before Emit is called.
//
// Verified against a real compile + Jackson round-trip (spike, not an
// automated test — see spike/m1-codegen-smoke): generated records compile
// and (de)serialize correctly, but only once the caller's ObjectMapper
// registers JavaTimeModule AND disables SerializationFeature.
// WRITE_DATES_AS_TIMESTAMPS. Without the latter, Jackson's default is to
// write LocalDate as a [y,m,d] array and Instant as an epoch number —
// which would disagree with the TS emitter's "date"/"datetime" -> string
// mapping and break wire compatibility between a Java and a TS client for
// the exact same contract. This is an M3 (bindings) configuration
// requirement to carry forward, not something M1 codegen can enforce by
// itself since it only emits types, not an ObjectMapper.
package java

import (
	"fmt"
	"slices"
	"strings"

	"eiche/internal/codegen"
	"eiche/internal/core"
)

// Options configures the emitted files. Package is the Java package
// declaration to prepend (e.g. "com.example.jobs.model"); empty means no
// package statement, for callers that place output into the default
// package (fine for a quick look, not for real use).
type Options struct {
	Package string
}

// Emit lowers ir into one .java file per model, enum, and view. The
// returned map is filename -> full file content. Callers must run
// core.CheckNaming (and CheckTypes/CheckExpressions before that) and
// confirm it's diagnostic-free before calling Emit — this function does
// not re-validate reserved words or type references.
func Emit(ir *core.IR, opts Options) map[string]string {
	files := make(map[string]string, len(ir.Enums)+len(ir.Models)+len(ir.Views))

	for _, e := range ir.Enums {
		files[e.Name+".java"] = emitEnum(opts, e)
	}
	for _, m := range ir.Models {
		files[m.Name+".java"] = emitRecord(opts, m.Name, m.Fields)
	}
	for _, v := range ir.Views {
		base := findModel(ir, v.Base)
		if base == nil {
			continue // unresolvable view; core.CheckTypes should have already rejected this IR
		}
		files[v.Name+".java"] = emitRecord(opts, v.Name, viewFields(base, v))
	}

	return files
}

func findModel(ir *core.IR, name string) *core.IRModel {
	for i := range ir.Models {
		if ir.Models[i].Name == name {
			return &ir.Models[i]
		}
	}
	return nil
}

// viewFields computes the field list a view's generated type should have:
// every base field forced optional for "partial", the named subset for a
// projection, or every base field unchanged for a full (bare) view.
func viewFields(base *core.IRModel, v core.IRView) []core.IRField {
	switch {
	case v.Partial:
		fields := make([]core.IRField, len(base.Fields))
		for i, f := range base.Fields {
			f.Optional = true
			fields[i] = f
		}
		return fields

	case len(v.Fields) > 0:
		want := make(map[string]bool, len(v.Fields))
		for _, name := range v.Fields {
			want[name] = true
		}
		var fields []core.IRField
		for _, f := range base.Fields {
			if want[f.Name] {
				fields = append(fields, f)
			}
		}
		return fields

	default:
		return base.Fields
	}
}

func emitEnum(opts Options, e core.IREnum) string {
	w := &codegen.Writer{}
	w.Line("// Code generated by eichec. DO NOT EDIT.")
	w.Blank()
	if opts.Package != "" {
		w.Line("package %s;", opts.Package)
		w.Blank()
	}
	w.Line("public enum %s {", e.Name)
	w.Indent()
	for i, m := range e.Members {
		if i == len(e.Members)-1 {
			w.Line("%s", m)
		} else {
			w.Line("%s,", m)
		}
	}
	w.Dedent()
	w.Line("}")
	return w.String()
}

func emitRecord(opts Options, name string, fields []core.IRField) string {
	type component struct {
		decl    string
		imports []string
	}
	components := make([]component, len(fields))
	importSet := map[string]bool{}
	for i, f := range fields {
		decl, imports := componentDecl(f)
		components[i] = component{decl: decl, imports: imports}
		for _, imp := range imports {
			importSet[imp] = true
		}
	}

	imports := make([]string, 0, len(importSet))
	for imp := range importSet {
		imports = append(imports, imp)
	}
	slices.Sort(imports)

	w := &codegen.Writer{}
	w.Line("// Code generated by eichec. DO NOT EDIT.")
	w.Blank()
	if opts.Package != "" {
		w.Line("package %s;", opts.Package)
		w.Blank()
	}
	for _, imp := range imports {
		w.Line("import %s;", imp)
	}
	if len(imports) > 0 {
		w.Blank()
	}

	if len(components) == 0 {
		w.Line("public record %s() {}", name)
		return w.String()
	}

	w.Line("public record %s(", name)
	w.Indent()
	for i, c := range components {
		if i == len(components)-1 {
			w.Line("%s", c.decl)
		} else {
			w.Line("%s,", c.decl)
		}
	}
	w.Dedent()
	w.Line(") {}")
	return w.String()
}

// componentDecl renders one record component: its Jackson/nullability
// annotations, its Java type, and its name — plus the fully-qualified
// imports those annotations and type require.
func componentDecl(f core.IRField) (string, []string) {
	typeStr, imports := javaFieldType(f.Type, f.Optional)

	var annotations []string
	if f.Optional {
		annotations = append(annotations, "@Nullable")
		imports = append(imports, "jakarta.annotation.Nullable")
	}
	// Explicit even where field names would already match: relying on the
	// canonical constructor's parameter names being visible on records
	// requires callers to compile with -parameters, which generated code
	// shouldn't assume.
	annotations = append(annotations, fmt.Sprintf("@JsonProperty(%q)", f.Name))
	imports = append(imports, "com.fasterxml.jackson.annotation.JsonProperty")

	decl := strings.Join(annotations, " ") + " " + typeStr + " " + f.Name
	return decl, imports
}

func javaFieldType(t core.IRType, optional bool) (string, []string) {
	if t.IsArray {
		elemSimple, elemImport := scalarJavaType(t.Scalar, true) // generics require reference types
		imports := []string{"java.util.List"}
		if elemImport != "" {
			imports = append(imports, elemImport)
		}
		return fmt.Sprintf("List<%s>", elemSimple), imports
	}

	simple, imp := scalarJavaType(t.Scalar, optional)
	var imports []string
	if imp != "" {
		imports = append(imports, imp)
	}
	return simple, imports
}

// scalarJavaType maps one non-array scalar to its Java simple name and
// the import it needs (empty for java.lang types, primitives, and
// same-package enum/model references). boxed forces the reference-type
// form (Integer, not int) — required for array elements, and for any
// optional field since a record component can't be a nullable primitive.
func scalarJavaType(scalar string, boxed bool) (simpleName, importPath string) {
	switch scalar {
	case "string":
		return "String", ""
	case "int":
		if boxed {
			return "Integer", ""
		}
		return "int", ""
	case "decimal":
		return "BigDecimal", "java.math.BigDecimal"
	case "bool":
		if boxed {
			return "Boolean", ""
		}
		return "boolean", ""
	case "date":
		return "LocalDate", "java.time.LocalDate"
	case "datetime":
		return "Instant", "java.time.Instant"
	case "json":
		return "JsonNode", "com.fasterxml.jackson.databind.JsonNode"
	default:
		// An enum or model name: every generated type lives in the same
		// package (one file per model/enum/view, all emitted together),
		// so no import is needed.
		return scalar, ""
	}
}
