// Package ts emits TypeScript interfaces, enum union types, and a barrel
// file from a checked IR. One file per model/enum/view, plus index.ts,
// per the M1 brief. Same scope cuts as internal/codegen/java: no
// validation annotations, defaults aren't applied here, "json" always
// maps to unknown regardless of an inline shape, and naming is the
// identity function — internal/core.CheckNaming must already have passed.
//
// Unlike Java, where same-package types need no import, every generated
// .ts file is its own module: referencing another generated type requires
// an explicit `import type`. That makes import collection do real work
// here, not just pull in a couple of stdlib types.
package ts

import (
	"fmt"
	"slices"

	"eiche/internal/codegen"
	"eiche/internal/core"
)

// Emit lowers ir into one .ts file per model, enum, and view, plus a
// barrel file (index.ts) re-exporting all of them. The returned map is
// filename -> full file content.
func Emit(ir *core.IR) map[string]string {
	files := make(map[string]string, len(ir.Enums)+len(ir.Models)+len(ir.Views)+1)

	for _, e := range ir.Enums {
		files[e.Name+".ts"] = emitEnum(e)
	}
	for _, m := range ir.Models {
		files[m.Name+".ts"] = emitInterface(m.Name, m.Fields)
	}
	for _, v := range ir.Views {
		base := findModel(ir, v.Base)
		if base == nil {
			continue // unresolvable view; core.CheckTypes should have already rejected this IR
		}
		files[v.Name+".ts"] = emitInterface(v.Name, viewFields(base, v))
	}
	files["index.ts"] = emitBarrel(ir)

	return files
}

func findModel(ir *core.IR, name string) *core.IRModel {
	for i := range ir.Models {
		if ir.Models[i].Name == name {
			return &ir.Models[i]
		}
	}
	return nil
}

// viewFields mirrors internal/codegen/java's: every base field forced
// optional for "partial", the named subset for a projection, or every
// base field unchanged for a full (bare) view.
func viewFields(base *core.IRModel, v core.IRView) []core.IRField {
	switch {
	case v.Partial:
		fields := make([]core.IRField, len(base.Fields))
		for i, f := range base.Fields {
			f.Optional = true
			fields[i] = f
		}
		return fields

	case len(v.Fields) > 0:
		want := make(map[string]bool, len(v.Fields))
		for _, name := range v.Fields {
			want[name] = true
		}
		var fields []core.IRField
		for _, f := range base.Fields {
			if want[f.Name] {
				fields = append(fields, f)
			}
		}
		return fields

	default:
		return base.Fields
	}
}

func emitEnum(e core.IREnum) string {
	w := &codegen.Writer{}
	w.Line("// Code generated by eichec. DO NOT EDIT.")
	w.Blank()

	literals := make([]string, len(e.Members))
	for i, m := range e.Members {
		literals[i] = fmt.Sprintf("%q", m)
	}

	if len(literals) == 0 {
		w.Line("export type %s = never;", e.Name)
		return w.String()
	}

	w.Line("export type %s =", e.Name)
	w.Indent()
	for i, lit := range literals {
		if i == len(literals)-1 {
			w.Line("%s;", lit)
		} else {
			w.Line("%s |", lit)
		}
	}
	w.Dedent()
	return w.String()
}

func emitInterface(name string, fields []core.IRField) string {
	type member struct {
		line     string
		crossRef string
	}
	members := make([]member, len(fields))
	importSet := map[string]bool{}
	for i, f := range fields {
		line, crossRef := fieldLine(f)
		members[i] = member{line: line, crossRef: crossRef}
		if crossRef != "" && crossRef != name {
			importSet[crossRef] = true
		}
	}

	imports := make([]string, 0, len(importSet))
	for imp := range importSet {
		imports = append(imports, imp)
	}
	slices.Sort(imports)

	w := &codegen.Writer{}
	w.Line("// Code generated by eichec. DO NOT EDIT.")
	w.Blank()
	for _, imp := range imports {
		w.Line(`import type { %s } from "./%s";`, imp, imp)
	}
	if len(imports) > 0 {
		w.Blank()
	}

	w.Line("export interface %s {", name)
	w.Indent()
	for _, m := range members {
		w.Line("%s", m.line)
	}
	w.Dedent()
	w.Line("}")
	return w.String()
}

// fieldLine renders one interface member and reports the cross-file type
// name it references, if any (empty for builtins).
func fieldLine(f core.IRField) (string, string) {
	tsType, crossRef := tsFieldType(f.Type)
	if f.Optional {
		return fmt.Sprintf("readonly %s?: %s;", f.Name, tsType), crossRef
	}
	return fmt.Sprintf("readonly %s: %s;", f.Name, tsType), crossRef
}

func tsFieldType(t core.IRType) (string, string) {
	if t.IsArray {
		elemType, crossRef := tsScalarType(t.Scalar)
		return fmt.Sprintf("readonly %s[]", elemType), crossRef
	}
	return tsScalarType(t.Scalar)
}

// tsScalarType maps one non-array scalar to its TS type and, for an
// enum/model/view reference, the name of the file it needs importing
// from (empty for every builtin).
func tsScalarType(scalar string) (tsType string, crossRef string) {
	switch scalar {
	case "string":
		return "string", ""
	case "int":
		return "number", ""
	case "decimal":
		// Preserves precision as the wire format for money; see the
		// brief's own open question about a branded type here later.
		return "string", ""
	case "bool":
		return "boolean", ""
	case "date", "datetime":
		return "string", "" // ISO 8601 on the wire
	case "json":
		return "unknown", ""
	default:
		return scalar, scalar
	}
}

func emitBarrel(ir *core.IR) string {
	w := &codegen.Writer{}
	w.Line("// Code generated by eichec. DO NOT EDIT.")
	w.Blank()

	var names []string
	for _, e := range ir.Enums {
		names = append(names, e.Name)
	}
	for _, m := range ir.Models {
		names = append(names, m.Name)
	}
	for _, v := range ir.Views {
		names = append(names, v.Name)
	}
	slices.Sort(names)

	for _, n := range names {
		w.Line(`export * from "./%s";`, n)
	}
	return w.String()
}
